version: "3.8"

services:
  db:
    image: postgres:15
    container_name: muslim_social_db
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: your_db_name
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: muslim_social_backend
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: your_db_user
      DB_PASS: your_db_password
      DB_NAME: your_db_name
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm run dev

volumes:
  postgres-data:
