const ApiStrings = {
  LOGIN: "/auth/login",
  REGISTER: "/auth/register",
  ME: "/auth/me",
  STATS: "/auth/stats",
  USER_DETAILS: (username:string) => `/auth/${username}/details`,
  LOGOUT: "/auth/logout",
  PRIVACY_SETTING: "/auth/privacy-settings",
  NOTIFICATION_PREFERENCE: "/auth/notification-preference",
  CHANGE_PASSWORD: "/auth/change-password",
  ENABLE_2FA: "/auth/2fa/enable",
  VERIFY_2FA: "/auth/2fa/verify",
  DISABLE_2FA: "/auth/2fa/disable",
  RECOVER_LOGIN: "/auth/recover-login",
  REQUEST_OTP: "/auth/request-otp",
  EMAIL_VERIFY_2FA: "/auth/2fa/email-verify",
  // Posts
  ALL_POSTS: '/post/',
  BOOKMARK_POSTS: '/post/bookmark/posts',
  FOLLOWING_ALL_POSTS: '/post/following/posts',
  EDITPOST: (id:number) => `/post/edit/${id}`,
  DELETEPOST: (id:number) => `/post/delete/${id}`,
  DELETE_MEDIA: (id:number) => `/post/delete/media/${id}`,
  REACTPOST: (id:number) => `/post/react/${id}`,
  SHAREPOST: (id:number) => `/post/share/${id}`,
  BOOKMARK_POST: (id:number) => `/post/bookmark/${id}`,
  USER_SUGGESTION: `/post/suggest`,
  // comments
  CREATE_COMMENT:(id:number) =>  `/comment/${id}`,
  EDIT_COMMENT:(id:number) =>  `/comment/edit/${id}`,
  REPLY_COMMENT:(id:number) =>  `/comment/reply/${id}`,
  DELETE_COMMENT:(id:number) =>  `/comment/delete/${id}`,
  COMMENT_REACT:(id:number) =>  `/comment/react/${id}`,
  GET_COMMENTS:(id:number) =>  `/comment/${id}/comments`,
  // Follow
  FOLLOW_UNFOLLOW:(id:number) =>  `/follow/${id}`,
  CREATE_STORY: `/follow/story/create`,
  DELETE_STORY: `/follow/story`,
  GET_STORIES: `/follow/stories`,
  // Conversation
  GET_CONVERSATION: `/conversation/`,
  GET_CONVERSATION_MESSAGE: (id:number) => `/conversation/${id}`,
  SEND_MESSAGE: `/conversation/send-message`,
  CREATE_CONVERSATION: `/conversation/create`,
  READ_MESSAGE: `/conversation/read-message`,
  SEND_ATTACHMENT: `/conversation/send-attachment`,
  DELETE_CONVERSATION: `/conversation/delete`,
  // stream
  INITIAL_CALL: '/stream/initiate-call',
  GET_LIVES: '/stream/',
  START_LIVE: '/stream/start',
  END_LIVE: '/stream/end',
  GET_CHATS: '/stream/chats',
  SEND_CHAT: '/stream/chat',
  GET_SHORTS: '/stream/shorts',
  UPLOAD_SHORT: '/stream/upload-short',
  DELETE_STREAM: '/stream/short',
  // report
  REPORT:'/report/',
  BAN_USER: (id:number) => `/report/ban/${id}`,
  // Notification
  GET_ALL_NOTIFICATION: '/notification',
  MARK_READ_NOTIFICATION: '/notification/mark-read',
};

export default ApiStrings;