const SocketEventEnum = Object.freeze({
  SOCKET_CONNECTED: "connected",
  SOCKET_DISCONNECTED: "disconnect",
  SOCKET_ERROR: "socketError",
  POST_REACT:"post_react",
  JOIN_POST: "joinPost",
  COMMENT_REACT:"commentReact",
  CREATE_COMMENT:"createComment",
  EDITED_COMMENT:"edited_comment",
  REPLY_COMMENT:"replyComment",
  DELETE_COMMENT:"deleteComment",
  JOIN_CONVERSATION: "joinConversation",
  JOIN_LIVE_STREAM: "joinLiveStream",
  HOST_LEFT_LIVE_STREAM: "hostLeftLiveStream",
  HOST_JOIN_LIVE_STREAM: "hostJointLiveStream",
  HOST_END_LIVE_STREAM: "hostEndLiveStream",
  SEND_MESSAGE_TO_CONVERSATION:"sendMessageToConversation",
  SEND_CONVERSATION_REQUEST:"addConversation",
  MESSAGE_RECEIVED:"messageReceived",
  TYPING:"typing:start",
  DISPLAY_TYPING:"displayTyping",
  ONLINE:"user:online",
  OFFLINE:"user:offline",
  OUTGOING_CALL:"outgoing:call",
  INCOMING_CALL:"incoming:call",
  CALL_REJECTED:"call:rejected",
  CALL_ACCEPTED:"call:accepted",
  CALLER_LEFT:"caller_left",
  CALL_TIMEOUT:"call_timeout",
  LIVE_VIEW_COUNT:'liveViewCount'
});

export default SocketEventEnum